esphome:
  name: ped-sign
  friendly_name: Ped Sign

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<key here>"

ota:
  password: "<ota here>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ped-Sign Fallback Hotspot"
    password: "<secret here>"

captive_portal:

# globals to keep track of state
globals:
  - id: counter
    type: int
    initial_value: '0'
  - id: dontwalk
    type: int
    initial_value: '0'
  - id: poweron
    type: int
    initial_value: '0'


switch:
  - platform: gpio   # the actual outputs to the sign
    id: walk
    pin:
      number: D1
  - platform: gpio
    id: hand
    pin:
      number: D2

  # the switches that show up in HA
  - platform: template
    name: "Enabled"
    id: "power"
    lambda: |-
      if (id(poweron) == 1) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - lambda: |-
          id(poweron) = 1;
    turn_off_action:
      - lambda: |-
          id(poweron) = 0;

  - platform: template
    name: "Don't Walk"
    lambda: |-
      if (id(dontwalk) == 1) {
        return true;
      } else {
        return false;
      }

    turn_on_action:
      - lambda: |-
          id(counter) = id(countdown).state * 2; // set the counter to the setting times two
          id(dontwalk) = 1;

  - platform: template
    name: "Walk"
    lambda: |-
      if (id(dontwalk) == 0) { 
        return true;
      } else {
        return false;
      }

    turn_on_action:
      - lambda: |-
          id(dontwalk) = 0;


interval:
  - interval: 500ms # twice a second
    then:
      - lambda: |-
          // if the power is on:
          if (id(poweron) != 1) {
            // turn off all power
            id(hand).turn_off();
            id(walk).turn_off();
            return;
          }

          // are we in walk?
          if (id(dontwalk) == 0) {
            // turn on the walk sign
            id(hand).turn_off();
            id(walk).turn_on();
            return;
          }

          // are we currently counting down?
          // and also are we in the half phase?
          if (id(counter) > 0) {
            if (id(counter) % 2 == 0) {
              // turn both off
              id(hand).turn_off();
              id(walk).turn_off();
              // decrement
              id(counter) = id(counter) - 1;
              return;
            }

            // decrement
            id(counter) = id(counter) - 1;
          } 

          id(hand).turn_on();
          id(walk).turn_off();


number:
  - platform: template
    name: "Countdown Duration"
    id: countdown
    max_value: 99
    min_value: 2
    optimistic: true
    step: 1